import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Roldrive",
  description: "Generated by create next app"
};
export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-lf-200  w-screen   text-white">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
